//! MySQL **예약어**(reserved word) 집합.
//!
//! # 왜 예약어만 넣는가 — 오류 방향이 비대칭이다
//!
//! `fold_ident` 가 비예약어를 소문자로 접으므로, 이 집합의 오류는 한쪽만 위험하다.
//!
//! | 실수 | 예 | 원문 | `DIGEST_TEXT` | 결과 |
//! |---|---|---|---|---|
//! | **누락** (예약어를 빼먹음) | `LATERAL` 없음 | `lateral` → `lateral` | `LATERAL` → `lateral` | **수렴한다.** 무해 |
//! | **과잉** (비예약어를 넣음) | `STATUS` 추가 | `status` → `STATUS` | `` `status` `` → `status` | **갈라진다.** 그룹핑 붕괴 |
//!
//! 그래서 확신하는 것만 넣는다. 비예약어(`STATUS`, `DATE`, `TIMESTAMP`, `COUNT`, `DATA`,
//! `TYPE`, `VALUE`, `TEXT`, `USER`, `SOURCE`, `START`, `END`, `LEVEL`, `NAME` 등)는
//! **절대 넣지 않는다** — 인용 없이 컬럼명으로 쓸 수 있는 단어들이다.
//!
//! 목록은 MySQL 8.0 / 8.4 의 예약어를 기준으로 한다([ADR-019](../../../docs/03-decisions.md)
//! 의 버전 하한). `INTERSECT`·`EXCEPT`(8.0.31+), `ARRAY`·`MEMBER`(8.0.17+),
//! `SOURCE_BIND`(8.4) 를 포함한다.
//!
//! `MASTER_*` / `SOURCE_*` 는 MySQL 문법 토큰을 그대로 인용한 것이며 우리가 고른 이름이 아니다.

/// 이진 탐색을 위해 **ASCII 대문자 정렬**을 유지해야 한다. `sorted_invariant` 테스트가 강제한다.
static RESERVED: &[&str] = &[
    "ADD",
    "ALL",
    "ALTER",
    "ANALYZE",
    "AND",
    "ARRAY",
    "AS",
    "ASC",
    "ASENSITIVE",
    "BEFORE",
    "BETWEEN",
    "BIGINT",
    "BINARY",
    "BLOB",
    "BOTH",
    "BY",
    "CALL",
    "CASCADE",
    "CASE",
    "CHANGE",
    "CHAR",
    "CHARACTER",
    "CHECK",
    "COLLATE",
    "COLUMN",
    "CONDITION",
    "CONSTRAINT",
    "CONTINUE",
    "CONVERT",
    "CREATE",
    "CROSS",
    "CUBE",
    "CUME_DIST",
    "CURRENT_DATE",
    "CURRENT_TIME",
    "CURRENT_TIMESTAMP",
    "CURRENT_USER",
    "CURSOR",
    "DATABASE",
    "DATABASES",
    "DAY_HOUR",
    "DAY_MICROSECOND",
    "DAY_MINUTE",
    "DAY_SECOND",
    "DEC",
    "DECIMAL",
    "DECLARE",
    "DEFAULT",
    "DELAYED",
    "DELETE",
    "DENSE_RANK",
    "DESC",
    "DESCRIBE",
    "DETERMINISTIC",
    "DISTINCT",
    "DISTINCTROW",
    "DIV",
    "DOUBLE",
    "DROP",
    "DUAL",
    "EACH",
    "ELSE",
    "ELSEIF",
    "EMPTY",
    "ENCLOSED",
    "ESCAPED",
    "EXCEPT",
    "EXISTS",
    "EXIT",
    "EXPLAIN",
    "FALSE",
    "FETCH",
    "FIRST_VALUE",
    "FLOAT",
    "FLOAT4",
    "FLOAT8",
    "FOR",
    "FORCE",
    "FOREIGN",
    "FROM",
    "FULLTEXT",
    "FUNCTION",
    "GENERATED",
    "GET",
    "GRANT",
    "GROUP",
    "GROUPING",
    "GROUPS",
    "HAVING",
    "HIGH_PRIORITY",
    "HOUR_MICROSECOND",
    "HOUR_MINUTE",
    "HOUR_SECOND",
    "IF",
    "IGNORE",
    "IN",
    "INDEX",
    "INFILE",
    "INNER",
    "INOUT",
    "INSENSITIVE",
    "INSERT",
    "INT",
    "INT1",
    "INT2",
    "INT3",
    "INT4",
    "INT8",
    "INTEGER",
    "INTERSECT",
    "INTERVAL",
    "INTO",
    "IO_AFTER_GTIDS",
    "IO_BEFORE_GTIDS",
    "IS",
    "ITERATE",
    "JOIN",
    "JSON_TABLE",
    "KEY",
    "KEYS",
    "KILL",
    "LAG",
    "LAST_VALUE",
    "LATERAL",
    "LEAD",
    "LEADING",
    "LEAVE",
    "LEFT",
    "LIKE",
    "LIMIT",
    "LINEAR",
    "LINES",
    "LOAD",
    "LOCALTIME",
    "LOCALTIMESTAMP",
    "LOCK",
    "LONG",
    "LONGBLOB",
    "LONGTEXT",
    "LOOP",
    "LOW_PRIORITY",
    "MASTER_BIND",
    "MASTER_SSL_VERIFY_SERVER_CERT",
    "MATCH",
    "MAXVALUE",
    "MEDIUMBLOB",
    "MEDIUMINT",
    "MEDIUMTEXT",
    "MEMBER",
    "MIDDLEINT",
    "MINUTE_MICROSECOND",
    "MINUTE_SECOND",
    "MOD",
    "MODIFIES",
    "NATURAL",
    "NOT",
    "NO_WRITE_TO_BINLOG",
    "NTH_VALUE",
    "NTILE",
    "NULL",
    "NUMERIC",
    "OF",
    "ON",
    "OPTIMIZE",
    "OPTIMIZER_COSTS",
    "OPTION",
    "OPTIONALLY",
    "OR",
    "ORDER",
    "OUT",
    "OUTER",
    "OUTFILE",
    "OVER",
    "PARTITION",
    "PERCENT_RANK",
    "PRECISION",
    "PRIMARY",
    "PROCEDURE",
    "PURGE",
    "RANGE",
    "RANK",
    "READ",
    "READS",
    "READ_WRITE",
    "REAL",
    "RECURSIVE",
    "REFERENCES",
    "REGEXP",
    "RELEASE",
    "RENAME",
    "REPEAT",
    "REPLACE",
    "REQUIRE",
    "RESIGNAL",
    "RESTRICT",
    "RETURN",
    "REVOKE",
    "RIGHT",
    "RLIKE",
    "ROW",
    "ROWS",
    "ROW_NUMBER",
    "SCHEMA",
    "SCHEMAS",
    "SECOND_MICROSECOND",
    "SELECT",
    "SENSITIVE",
    "SEPARATOR",
    "SET",
    "SHOW",
    "SIGNAL",
    "SMALLINT",
    "SOURCE_BIND",
    "SOURCE_SSL_VERIFY_SERVER_CERT",
    "SPATIAL",
    "SPECIFIC",
    "SQL",
    "SQLEXCEPTION",
    "SQLSTATE",
    "SQLWARNING",
    "SQL_BIG_RESULT",
    "SQL_CALC_FOUND_ROWS",
    "SQL_SMALL_RESULT",
    "SSL",
    "STARTING",
    "STORED",
    "STRAIGHT_JOIN",
    "SYSTEM",
    "TABLE",
    "TERMINATED",
    "THEN",
    "TINYBLOB",
    "TINYINT",
    "TINYTEXT",
    "TO",
    "TRAILING",
    "TRIGGER",
    "TRUE",
    "UNDO",
    "UNION",
    "UNIQUE",
    "UNLOCK",
    "UNSIGNED",
    "UPDATE",
    "USAGE",
    "USE",
    "USING",
    "UTC_DATE",
    "UTC_TIME",
    "UTC_TIMESTAMP",
    "VALUES",
    "VARBINARY",
    "VARCHAR",
    "VARCHARACTER",
    "VARYING",
    "VIRTUAL",
    "WHEN",
    "WHERE",
    "WHILE",
    "WINDOW",
    "WITH",
    "WRITE",
    "XOR",
    "YEAR_MONTH",
    "ZEROFILL",
];

pub fn is_reserved(word: &str) -> bool {
    // 대문자 변환을 스택 버퍼로 처리해 할당을 피한다. 예약어는 모두 ASCII 30자 미만이다.
    let mut buf = [0u8; 32];
    let bytes = word.as_bytes();
    if bytes.len() > buf.len() || !word.is_ascii() {
        return false;
    }
    for (i, b) in bytes.iter().enumerate() {
        buf[i] = b.to_ascii_uppercase();
    }
    let upper = std::str::from_utf8(&buf[..bytes.len()]).unwrap_or("");
    RESERVED.binary_search(&upper).is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sorted_invariant() {
        // 이진 탐색이 정렬을 전제한다. 항목 추가 시 이 테스트가 실수를 잡는다.
        for w in RESERVED.windows(2) {
            assert!(w[0] < w[1], "정렬 위반: {:?} 뒤에 {:?}", w[0], w[1]);
        }
    }

    #[test]
    fn recognizes_reserved_case_insensitively() {
        for w in [
            "select",
            "SELECT",
            "Select",
            "order",
            "values",
            "in",
            "intersect",
        ] {
            assert!(is_reserved(w), "{w} 는 예약어여야 한다");
        }
    }

    #[test]
    fn rejects_non_reserved() {
        // 이 단어들이 들어가면 수렴성이 깨진다 (모듈 문서의 "과잉" 행).
        for w in [
            "status",
            "date",
            "timestamp",
            "datetime",
            "count",
            "data",
            "type",
            "value",
            "text",
            "user",
            "source",
            "start",
            "end",
            "level",
            "name",
            "comment",
            "enum",
            "any",
            "some",
            "local",
            "global",
            "session",
            "first",
            "last",
            "next",
        ] {
            assert!(!is_reserved(w), "{w} 는 비예약어라 제외해야 한다");
        }
    }

    #[test]
    fn handles_oversized_and_non_ascii_input() {
        assert!(!is_reserved(&"x".repeat(64)));
        assert!(!is_reserved("주문"));
    }
}
